# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.
Integrated with YOLO segmentation for drop detection, LangChain for recovery decisions,
and Speech-to-Text for voice input.
"""

import logging
import time
import socket
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data

# YOLO, LangChain, and Speech Recognition imports
from ultralytics import YOLO
import numpy as np
import torch
import os
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_deepseek import ChatDeepSeek
import speech_recognition as sr


# ============================================================================
# SPEECH-TO-TEXT FUNCTIONS
# ============================================================================

def check_internet_connection(host="8.8.8.8", port=53, timeout=3):
    """
    Checks if there is an active internet connection by trying to 
    connect to a public DNS server (Google DNS).
    """
    try:
        socket.setdefaulttimeout(timeout)
        socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((host, port))
        return True
    except socket.error:
        return False


def get_user_input_with_voice(question: str) -> str:
    """
    Logic:
    1. Check Internet.
    2. Wait 3s for speech to START (timeout).
    3. If speech starts, listen indefinitely.
    4. If speech STOPS, wait 3s for more speech (pause_threshold).
    5. If silence persists for 3s after speech, process text.
    6. Fallback to text input on errors or timeout.
    """
    
    # 1. Check Internet Connection First
    if not check_internet_connection():
        logging.warning("\n[!] No internet connection detected.")
        logging.warning("    Skipping voice recognition. Please type your response.\n")
        return input(f"{question} (Text): ")

    # 2. Initialize Recognizer
    recognizer = sr.Recognizer()
    
    # CONFIGURATION FOR TIMING
    # Wait 3 seconds of silence AFTER speaking stops before finalizing the phrase
    recognizer.pause_threshold = 3.0 
    
    try:
        with sr.Microphone() as source:
            print(f"\n{question}")
            print("    🎤 Listening... (3s to start, 3s silence to end)")
            
            # Adjust for ambient noise quickly
            recognizer.adjust_for_ambient_noise(source, duration=0.3)
            
            # 3. Listen with specific timeouts
            # timeout=3: Max time to wait for speech to START
            # phrase_time_limit=None: No max limit on how long you can talk
            audio = recognizer.listen(source, timeout=3, phrase_time_limit=None)
            
            print("    Processing voice...")
            
            # Convert speech to text using Google
            text = recognizer.recognize_google(audio)
            print(f"    ✅ Voice detected: '{text}'")
            return text

    except sr.WaitTimeoutError:
        # 4. Fallback: Triggered if 3 seconds pass at the START with no speech
        logging.warning("\n    ⏱️  No speech started within 3 seconds.")
        return input(f"{question} (Text): ")
        
    except sr.UnknownValueError:
        logging.warning("\n    ❌ Could not understand audio.")
        return input(f"{question} (Text): ")
        
    except sr.RequestError:
        logging.warning("\n    ❌ Voice API request failed.")
        return input(f"{question} (Text): ")
        
    except OSError:
        logging.warning("\n    ❌ Microphone not accessible.")
        return input(f"{question} (Text): ")


# ============================================================================
# LANGCHAIN DROP RECOVERY FUNCTIONS
# ============================================================================

def classify_drop_recovery_intent(user_reply: str, llm: ChatDeepSeek | None = None) -> str:
    """
    Uses LLM to classify user intent after drop detection.
    Returns: "restart" or "exit"
    """
    if llm is None:
        # Fallback to simple keyword matching if LangChain not available
        reply_lower = user_reply.lower()
        if any(word in reply_lower for word in ["restart", "retry", "again", "yes", "continue", "pick", "resume"]):
            return "restart"
        else:
            return "exit"
    
    prompt = f"""
    You are a binary classifier for robot drop recovery. The user is responding to:
    "What should I do now, as I might have dropped the item?"
    
    User reply: "{user_reply}"
    
    Classify into EXACTLY one of these two options:
    - "restart" → User wants to retry picking up the item
    - "exit" → User wants to stop the program
    
    Reply with ONLY one word: "restart" or "exit".
    If unclear, default to "exit" for safety.
    """
    
    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        decision = response.content.strip().lower()
        
        # Extract just the keyword if LLM adds extra text
        if "restart" in decision:
            decision = "restart"
        elif "exit" in decision:
            decision = "exit"
        else:
            decision = "exit"  # Default to safe option
        
        logging.info(f"🦜 [LangChain Intent] Input: '{user_reply}' → Decision: {decision}")
        return decision
    except Exception as e:
        logging.warning(f"⚠ LangChain classification failed: {e}, using fallback")
        return classify_drop_recovery_intent(user_reply, llm=None)


def get_user_decision_with_langchain(events: dict, llm: ChatDeepSeek | None = None) -> str:
    """
    Pause execution and wait for user input (voice or text), then classify with LangChain.
    Returns: "restart" or "exit"
    """
    print("\n" + "="*100)
    print("🤖 ROBOT: What should I do now, as I might have dropped the item?")
    print("="*100)
    print("Options:")
    print("  - Type 'restart' or 'retry' to pick up the item again")
    print("  - Type 'exit' or 'stop' to end the program")
    print("  - Or describe in natural language (e.g., 'yes please try again', 'no just stop')")
    print("  - 🎤 You can also SPEAK your response (3s to start, 3s silence to end)")
    print("="*100)
    
    try:
        # 🎤 Get user input via voice (with text fallback)
        user_reply = get_user_input_with_voice("\nYour response (voice or text): ")
        
        if not user_reply:
            logging.warning("⚠ Empty input, defaulting to exit for safety")
            return "exit"
        
        # Classify intent using LangChain
        decision = classify_drop_recovery_intent(user_reply, llm)
        
        print("\n" + "-"*100)
        print(f"🦜 Decision classified as: {decision.upper()}")
        print("-"*100 + "\n")
        
        return decision
    except KeyboardInterrupt:
        logging.warning("⚠ User interrupted with Ctrl+C, defaulting to exit")
        return "exit"
    except Exception as e:
        logging.error(f"❌ Error getting user decision: {e}")
        return "exit"


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
    segmentation_model: YOLO | None = None,  # Added for drop detection
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    # Initialize drop detection state variables (reset each episode)
    has_item_detected = False
    drop_counter = 0

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        # Drop detection logic - check segmentation_disabled flag
        if segmentation_model is not None and not events.get("segmentation_disabled", False):
            try:
                # Find camera image
                camera_image = None
                for key in ["camera1", "image", "observation/image", "pixels", "observation/camera1"]:
                    if key in obs:
                        camera_image = obs[key]
                        break
                
                if camera_image is not None:
                    # Preprocess image for YOLO
                    if hasattr(camera_image, 'cpu'):
                        camera_image = camera_image.cpu().numpy()
                    if hasattr(camera_image, 'numpy'):
                        camera_image = camera_image.numpy()
                    if camera_image.dtype in [np.float32, np.float64] and camera_image.max() <= 1.0:
                        camera_image = (camera_image * 255).astype(np.uint8)
                    if camera_image.ndim == 3 and camera_image.shape[0] in [1, 3]:
                        camera_image = np.transpose(camera_image, (1, 2, 0))
                    
                    # Run inference
                    results = segmentation_model(camera_image, verbose=False, conf=0.25, 
                                               device='cuda' if torch.cuda.is_available() else 'cpu')
                    
                    if len(results) > 0 and results[0].boxes is not None and len(results[0].boxes) > 0:
                        result = results[0]
                        classes = result.boxes.cls.cpu().numpy()
                        confidences = result.boxes.conf.cpu().numpy()
                        
                        # KEY FIX: Only consider has_item (1) and no_item (2) for drop logic
                        # Ignore robotic_arm (0) completely in state machine decisions
                        valid_indices = [i for i, cls in enumerate(classes) if int(cls) in [1, 2]]
                        
                        if valid_indices:
                            # Pick the detection with HIGHEST CONFIDENCE among valid classes
                            best_idx = max(valid_indices, key=lambda i: confidences[i])
                            best_class_id = int(classes[best_idx])
                            best_conf = confidences[best_idx]
                            
                            class_names = ["robotic_arm", "has_item", "no_item"]
                            detected_class = class_names[best_class_id]
                            
                            # Debug log: show decision-making process
                            logging.info(f"🎯 [{timestamp:.1f}s] '{detected_class}' (conf:{best_conf:.2f}) | State: caught={has_item_detected}, counter={drop_counter}")
                            
                            # State machine for drop detection
                            if detected_class == "has_item":
                                # Item is caught - enable monitoring and reset counter
                                if not has_item_detected:
                                    logging.info(f"✅ [{timestamp:.1f}s] 🟢 ITEM CAUGHT - Starting drop monitoring")
                                has_item_detected = True
                                drop_counter = 0  # Reset whenever item is re-detected
                                
                            elif detected_class == "no_item":
                                # Item potentially dropped
                                if has_item_detected:
                                    drop_counter += 1
                                    logging.warning(f"⚠️ [{timestamp:.1f}s] 🔴 DROP: {drop_counter}/10 frames")
                                    if drop_counter >= 10:
                                        logging.critical(f"❌ [{timestamp:.1f}s] 💥 Dropped for 10+ consecutive frames")
                                        events["drop_detected"] = True
                                        events["waiting_for_user"] = True  # Pause and wait for user
                                        break  # Exit loop to trigger user prompt
                                # If hasn't caught item yet, ignore no_item detections
                                
                        else:
                            # Only robotic_arm detected or no detections - log occasionally
                            if int(timestamp) % 3 == 0:
                                logging.info(f"🔍 [{timestamp:.1f}s] Only robotic_arm or no valid detections")
                    else:
                        if int(timestamp) % 3 == 0:
                            logging.info(f"🔍 [{timestamp:.1f}s] No segmentation detections")
                            
            except Exception as e:
                logging.error(f"❌ Segmentation error: {type(e).__name__}: {e}", exc_info=True)
                # Continue execution - don't stop robot if vision fails
        
        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        # Send action to robot
        _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(
                observation=obs_processed, action=action_values, compress_images=display_compressed_images
            )

        dt_s = time.perf_counter() - start_loop_t
        precise_sleep(max(1 / fps - dt_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        # Load YOLO segmentation model for drop detection
        segmentation_model_path = r"C:\School Stuff\Year 4 Sem 2\FYP\lerobotFYP\imagesegthings\runs\segment\actual_segmentation_500epochs\weights\best.pt"
        segmentation_model = None
        if os.path.exists(segmentation_model_path):
            try:
                segmentation_model = YOLO(segmentation_model_path)
                logging.info(f"✓ Loaded segmentation model from {segmentation_model_path}")
            except Exception as e:
                logging.error(f"✗ Failed to load segmentation model: {e}")
        else:
            logging.warning(f"⚠ Segmentation model not found at {segmentation_model_path}, drop detection disabled")

        # 🦜 Initialize LangChain for drop recovery conversation
        load_dotenv()  # Load DEEPSEEK_API_KEY from .env
        langchain_llm = None
        if os.getenv("DEEPSEEK_API_KEY"):
            try:
                langchain_llm = ChatDeepSeek(
                    api_key=os.getenv("DEEPSEEK_API_KEY"),
                    model="deepseek-chat",
                    temperature=0,
                )
                logging.info("✓ LangChain initialized with DeepSeek")
            except Exception as e:
                logging.warning(f"⚠ Failed to initialize LangChain: {e}")
        else:
            logging.warning("⚠ DEEPSEEK_API_KEY not found in .env, LangChain disabled")

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()
        events["drop_detected"] = False
        events["waiting_for_user"] = False
        events["user_decision"] = None
        events["segmentation_disabled"] = False

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                    segmentation_model=segmentation_model,
                )

                # 🦜 HANDLE DROP RECOVERY WITH LANGCHAIN
                if events.get("drop_detected", False) and events.get("waiting_for_user", False):
                    events["waiting_for_user"] = False
                    
                    log_say("Item dropped, waiting for your decision", cfg.play_sounds)
                    
                    user_decision = get_user_decision_with_langchain(events, langchain_llm)
                    events["user_decision"] = user_decision
                    
                    if user_decision == "restart":
                        log_say("Restarting episode, please reset the item", cfg.play_sounds)
                        logging.info("🔄 User chose to RESTART - Clearing episode buffer")
                        
                        # 🚫 DISABLE SEGMENTATION during reset/re-record wait
                        events["segmentation_disabled"] = True
                        
                        dataset.clear_episode_buffer()
                        events["exit_early"] = False
                        events["drop_detected"] = False
                        
                        log_say("Reset the environment", cfg.play_sounds)
                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                            segmentation_model=segmentation_model,
                        )
                        
                        log_say("Press left arrow to re-record episode", cfg.play_sounds)
                        logging.info("⏳ Waiting for user to press left arrow to re-record...")
                        
                        # Continue waiting in reset_loop until user presses left arrow
                        # Segmentation is disabled during this wait
                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                            segmentation_model=segmentation_model,
                        )
                        
                        # ✅ RE-ENABLE SEGMENTATION for the new recording attempt
                        events["segmentation_disabled"] = False
                        events["exit_early"] = False
                        
                        # Continue to next iteration without incrementing recorded_episodes
                        continue
                        
                    elif user_decision == "exit":
                        log_say("Exiting program as requested", cfg.play_sounds)
                        logging.info("🛑 User chose to EXIT - Stopping recording")
                        events["stop_recording"] = True
                        break  # Exit main recording loop

                # Execute reset between episodes (normal flow, not drop recovery)
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    # reset g1 robot
                    if robot.name == "unitree_g1":
                        robot.reset()

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        segmentation_model=segmentation_model,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        # 🚫 NO HOME POSITION RESET - Just disconnect directly
        logging.info("🔌 Disconnecting robot...")

        if dataset:
            # 🚫 SKIP SAVING IF DROP DETECTED AND USER CHOSE EXIT
            if events.get("drop_detected", False) and events.get("user_decision") == "exit":
                logging.warning("⚠ Drop detected + User chose exit - Skipping dataset save and upload")
                dataset = None
            else:
                dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        # 🚫 SKIP HUB UPLOAD IF DROP DETECTED AND USER CHOSE EXIT
        if cfg.dataset.push_to_hub and not (events.get("drop_detected", False) and events.get("user_decision") == "exit"):
            if dataset:
                dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()